version: "3.6"
services:
  # API services
  app:
    restart: always
    build: .
    ports:
      - 8081:8081
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
    links:
      - mongo
    depends_on:
      - mongo
    networks:
        - app-network
  # Database
  mongo:
    container_name: mongo
    image: mongo
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017
    networks:
        - app-network

volumes:
  mongodb_data_container:

networks:
  app-network:
    driver: bridge
